services:
  db:
    image: postgres:15-alpine
    container_name: PASAR_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PASAR_db
    ports:
      - "5433:5432"
    volumes:
      # Links init.sql so it creates the tables
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # The Volume
      - PASARdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d PASAR_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: spring_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Images:/app/Images
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/PASAR_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  PASARdb_data: